#### Create a new User 
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "qwasdasdqwqwe"
}

#### SingIn a User 
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "qwasdasdqwqwe"
}

#### Get current user 
GET http://localhost:3000/auth/whoami

#### signout  user 
GET http://localhost:3000/auth/signout



#### Update a User 
PATCH  http://localhost:3000/auth/1
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "qwasdasdqwqwe"
}

#### Update a User Email
PATCH  http://localhost:3000/auth/2
Content-Type: application/json

{
    "email": "test4@test.com"
}

#### Update a  User password
PATCH  http://localhost:3000/auth/100
Content-Type: application/json

{
    "password": "qwasdasdqwqwe2"
}


#### Get  User 
GET http://localhost:3000/auth/1

#### Get  User 
GET http://localhost:3000/auth/100

#### Delete  User 
DELETE  http://localhost:3000/auth/300

#### Get All  Users 
GET http://localhost:3000/auth/

#### Get users by email 
GET http://localhost:3000/auth/?email=test2@test.com

#### Get users by email 
GET http://localhost:3000/auth/?email=dsdsdsd@test.com




